# pnpm workspace 配置
# 用于管理 CLI 项目依赖版本

gitChecks: false
registry: https://registry.npmjs.org/

packages:
  - __test__
  - templates/common/base
  - templates/common/features/*
  - templates/vue/base
  - templates/vue/features/*
  - templates/vue/micro-frontends/qiankun/base
  - templates/vue/micro-frontends/qiankun/features/*
  - templates/react/base
  - templates/react/features/*
  - templates/react/micro-frontends/qiankun/base
  - templates/react/micro-frontends/qiankun/features/*
catalogs:
  build:
    chalk: ^5.3.0
    commander: ^12.1.0
    fs-extra: ^11.3.0
    inquirer: ^12.0.0
    ora: ^8.1.1
  dev:
    '@commitlint/cli': ^19.8.0
    '@commitlint/config-conventional': ^19.8.0
    '@moluoxixi/eslint-config': 0.0.19
    commitizen: ^4.3.1
    cz-customizable: ^7.4.0
    eslint: ^10.0.0
    husky: ^9.1.7
    jiti: ^2.4.2
    lint-staged: ^15.5.1
    tsx: ^4.20.5
    typescript: ~5.8.0
    vite: ^6.2.4
  type:
    '@types/fs-extra': ^11.0.4
    '@types/inquirer': ^9.0.7
    '@types/node': ^22.14.0
  conflicts_dev_6_2_4:
    vite: 6.2.4
  conflicts_dev_h9_22_0:
    eslint: ^9.22.0
catalog:
  '@ant-design/icons': ^5.5.1
  '@ant-design/icons-vue': ^7.0.1
  '@commitlint/types': ^19.8.0
  '@element-plus/icons-vue': ^2.3.1
  '@sentry/react': ^9.27.0
  '@sentry/vite-plugin': ^3.5.0
  '@sentry/vue': ^9.27.0
  '@tailwindcss/postcss': ^4.0.0
  '@types/crypto-js': ^4.2.2
  '@types/lodash-es': ^4.17.12
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  '@types/uuid': ^10.0.0
  '@vitejs/plugin-react': ^4.3.4
  '@vitejs/plugin-vue': ^5.2.1
  ant-design-vue: ^4.2.1
  antd: ^5.22.0
  autoprefixer: ^10.4.20
  axios: ^1.16.1
  compressing: ^1.10.1
  crypto-js: ^4.2.0
  dayjs: ^1.11.13
  dotenv: ^16.5.0
  element-plus: ^2.11.3
  eslint-plugin-format: ^1.0.1
  i18next: ^24.0.0
  lodash-es: ^4.17.21
  pinia: ^2.2.7
  pinia-plugin-persistedstate: ^3.2.1
  postcss: ^8.5.3
  radash: ^12.1.0
  react: ^18.3.1
  react-dom: ^18.3.1
  react-i18next: ^15.1.0
  react-router-dom: ^7.1.3
  sass: ^1.87.0
  sass-embedded: ^1.87.0
  sass-loader: ^16.0.5
  tailwindcss: ^4.0.0
  unplugin-auto-import: ^19.1.2
  unplugin-vue-components: ^28.4.1
  uuid: ^11.1.0
  vite-plugin-pages: ^0.33.2
  vite-plugin-qiankun: ^1.0.15
  vue: ^3.5.13
  vue-i18n: ^11.1.10
  vue-router: ^4.4.5
  vue-tsc: ^3.0.0
  zustand: ^5.0.2
