name: Publish

# 基于分支发布，仅 main 分支可以发布
on:
  push:
    branches:
      - main
  # 之前 tag 的逻辑（已注释，个人测试用，暂时不想用 tag）
  # push:
  #   tags:
  #     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # Use Publish environment for deployment protection
    environment: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - run: pnpm install
      - run: pnpm publish --no-git-checks

